/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.79.0
  Forc version: 0.49.3
  Fuel-Core version: 0.22.1
*/

import type {
  BigNumberish,
  BN,
  Bytes,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
  StdString,
} from 'fuels';

export type RawBytesInput = { ptr: BigNumberish, cap: BigNumberish };
export type RawBytesOutput = { ptr: BN, cap: BN };

interface ValidityContractAbiInterface extends Interface {
  functions: {
    test_read_bytes: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'test_read_bytes', values: []): Uint8Array;

  decodeFunctionData(functionFragment: 'test_read_bytes', data: BytesLike): DecodedValue;
}

export class ValidityContractAbi extends Contract {
  interface: ValidityContractAbiInterface;
  functions: {
    test_read_bytes: InvokeFunction<[], [StdString, string, string, boolean, BN, number]>;
  };
}
